name: license_client
description: "Cliente simple para solicitar licencias a un servidor Widevine de demostración."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  pointycastle: ^4.0.0
  basic_utils: ^5.7.0
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0